"""Sanitised historical stage functions, explicit provider, guarded I/O and visible failures.

This is not a recovered rebuttal reproduction. Original prompts/3x3/best-QA preserved;
provider, input projection, bounded external calls and search/extraction are declared changes.
"""
from types import SimpleNamespace
from scripts.relevancy_checker import assess_image_headline_relevancy
from scripts.visual_veracity_checker import assess_image_visual_veracity
from scripts.question_generator import generate_investigative_questions
from scripts.answer_generator import generate_answer_from_search
from scripts.qa_selector import select_best_qa_and_propose_followups
from scripts.ai_judge import _SYSTEM_PROMPT,_build_user_message
from scripts.redesign.clients import ProviderFailure
from scripts.redesign.payloads import probability
import json


class Bridge:
    def __init__(self,client,sample_id):self.client=client;self.sample_id=sample_id;self.calls=[];self.failed=False
    def get_model(self):return self
    def invoke(self,messages):
        if self.failed:raise ProviderFailure('Earlier stage failed; no more dispatch')
        try:
            r=self.client.native(self.sample_id,messages)
            self.calls.append(r)
            return SimpleNamespace(content=r['raw'])
        except Exception:
            self.failed=True
            raise
    def check(self):
        if self.failed:raise ProviderFailure('A historical stage swallowed a request failure')


def historical_baseline(sample,client,collect):
    sid=sample['sample_id'];headline=sample['headline'];path=str(sample['image_path'])
    bridge=Bridge(client,sid)
    rel=assess_image_headline_relevancy(path,headline,bridge)
    vis=assess_image_visual_veracity(path,bridge)
    prior=[];all_answers={};best=[];retrieval=[]
    for _ in range(3):
        qres=generate_investigative_questions(path,headline,bridge,chains=1,questions_per_chain=3,prior_questions=prior,prior_answers=all_answers)
        chain=qres['chains'][0];prior.extend(chain)
        answers={}
        for query in chain:
            if type(query) is not str:raise ProviderFailure('Malformed query')
            docs,status=collect(sid,query)
            retrieval.extend(status)
            if not docs:raise ProviderFailure('No usable factual evidence for historical baseline')
            search={'provider':'declared_common_stack','results':[{'title':'Source passage','url':r['url'],'description':r['text']} for r in docs[:5]]}
            answers[query]=generate_answer_from_search(query,search,bridge,max_sources=5)
        all_answers.update(answers)
        # Follow-ups are generated by the original function but not executed, as in main.py.
        selection=select_best_qa_and_propose_followups(path,headline,[chain],answers,bridge,followups_per_chain=3)
        bridge.check();best.extend(selection['selected'])
    final={'headline':headline,'relevancy':rel,'visual_veracity':vis,'best_qa_per_chain':best}
    response=bridge.invoke([{'role':'system','content':_SYSTEM_PROMPT},{'role':'user','content':_build_user_message(final)}])
    parsed=json.loads(response.content)
    if parsed.get('label') not in ('Misinformation','Not Misinformation'):raise ProviderFailure('Malformed baseline verdict')
    probability(parsed.get('confidence'))
    return {'sample_id':sid,'prediction':parsed['label'],'status':'OK','baseline':'MERIT_sanitised_historical_stages_v2','calls':bridge.calls,'retrieval':retrieval,'signals':final,'verdict':parsed}
